# docker-compose-end2endtest.yml

version: '3.7'
services:

  end2endtest:
    build:
      context: ./server/workers/tests
      dockerfile: ./Dockerfile_tests
    volumes:
      - ./server/:/app
    depends_on:
      - db
      - backend
    restart: "no"
    entrypoint: ["pytest", '/app/workers/tests/test_end2end.py', '-s', '-rfA']
    networks: 
      - test

  backend:
    build:
      context: ./server/workers/tests
      dockerfile: ./Dockerfile_backend
    volumes:
      - ./server/:/var/www/html/server
    restart: "no"
    networks: 
      - test
    ports:
      - "80:80"

  db:
    image: 'postgres:12.2-alpine'
    restart: "no"
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpassword"
    command: postgres -c config_file=/etc/postgresql.conf -c hba_file=/etc/pg_hba.conf
    volumes:
      # - db_data:/var/lib/postgresql/data
      - ./server/workers/example_pg_hba.conf:/etc/pg_hba.conf
      - ./server/workers/example_postgresql.conf:/etc/postgresql.conf
    networks: 
      - test

volumes:
  db_data:

networks:
  test: