services:
  composer:
    image: composer:2.8
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - ./server/classes/headstart:/app
    restart: never

  # PHP_CodeSniffer is a dev dependency of server/classes/headstart; install it with
  # the composer service first.
  phpcs:
    image: php:8.2-cli-trixie
    restart: never
    volumes:
      - ./server:/data
    working_dir: /data
    entrypoint: classes/headstart/vendor/bin/phpcs

  phpunit82:
    image: php:8.2-cli-trixie
    restart: never
    volumes:
      - ./server/classes/headstart:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
