export var intros = { 
    intro_hs: {
        title: "Head Start: Overview of Educational Technology",
        body: "<p>Head Start presents you with the main areas in the field, and lets you zoom into the most important publications within each area. It is intended to give researchers that are new to a field a head start on their literature review (hence the name)." + "<p><ul><li>The main areas in the field are represented by the blue bubbles.<li>Once you click on a bubble, you are presented with the main papers in that area.<li>The dropdown on the right displays the same data in list form. By clicking on one of the papers, you can access all metadata for that paper.<li>If a preview is available, you can retrieve it by clicking on the thumbnail in the metadata panel.<li>By clicking on the white background, you can then zoom out and inspect another area.</ul>" + "<p>The visualization was created with <a href=\"http://d3js.org/\" target=\"_blank\">D3.js</a>. It has been successfully tested with Chrome 22, Firefox 15, and Safari 5.1. Unfortunately, Internet Explorer and Opera are not supported at this point." + "<p>The visualization is based on readership co-occurrence. More information can be found in <a href=\"http://www.mendeley.com/research/harnessing-user-library-statistics-research-evaluation-knowledge-domain-visualization/\" target=\"_blank\">this paper</a>. You can contact the author at <a href=\"mailto:peter.kraker@tugraz.at\">peter.kraker@tugraz.at</a>."
    }, intro_cn3: {
        title: "Overview Visualization of EC-TEL and i-KNOW 2014",
        body: "<p>This visualization presents you with a topical overview of EC-TEL and i-KNOW 2014, and highlights papers that are recommended for you. You can inspect the papers within each topic, and bookmark papers of interest." + "<p><ul><li>The main conference topics are represented by the blue bubbles." + "<li>Once you click on a bubble, you zoom into the papers related to that topic." + "A <span style='background-color:green'>green</span> border around a paper indicates that you have already bookmarked this paper. A <span style='background-color:yellow'>yellow</span> border around a paper indicates that this paper is recommended for you" + "<li>By clicking on one of the papers, you can access all metadata for that paper and bookmark the paper in the right hand pane." + "<li>By clicking on the white background, you can then zoom out and inspect another area.</ul>" + "<p>The visualization is based on term co-occurrence. More information can be found in <a href='http://www.marshallplan.at/images/papers_scholarship/2014/Graz_KrakerPeter_2014.pdf' target='_blank'>this report</a> and in this <a href='http://www.mendeley.com/research/altmetricsbased-visualizations-depicting-evolution-knowledge-domain/' target='_blank'>this paper</a>. You can contact the author at <a href=\"mailto:peter.kraker@tugraz.at\">peter.kraker@tugraz.at</a>." + "<p>Head Start was created with <a href=\"http://d3js.org/\" target=\"_blank\">D3.js</a>. It has been successfully tested with Chrome 22, Firefox 15, Safari 5.1, and Opera 20. Unfortunately, Internet Explorer is not supported at this point." + "<h3>Acknowledgements</h3>" + "<p>The visualization was created with funding provided by European Commission as part of the FP7 Marie Curie IAPP project TEAM (grant no. 251514), the Austrian Marshallplan Foundation, the Open Knowledge Foundation, and the Know-Center. The Know-Center is funded within the Austrian COMET program - Competence Centers for Excellent Technologies - under the auspices of the Austrian Federal Ministry of Transport, Innovation and Technology, the Austrian Federal Ministry of Economy, Family and Youth, and the State of Styria. COMET is managed by the Austrian Research Promotion Agency FFG."
    }, intro_plos: {
        title: "Overview Visualization of a PLOS Search Result",
        body: "<p>This visualization presents you with a topical overview of the 100 most relevant papers for your PLOS search. You can inspect the papers within each topic, and read individual papers within this interface." + "<p><ul><li>The main topics, derived from PLOS subject areas, are represented by the blue bubbles." + "<li>Once you click on a bubble, you zoom into the papers related to that topic." + "<li>By clicking on one of the papers, you can access all metadata for that paper. By clicking on \"Preview PDF\", you can read the paper within the interface. By clicking on the title, you will be transferred to the paper on the PLOS website." + "<li>By clicking on the white background, you can then zoom out and inspect another area.</ul>" + "<p>The visualization is based on fulltext similarities. More information can be found in the <a href='http://github.com/pkraker/Headstart' target='_blank'>Github repo</a>. You can contact the maintainer at <a href=\"mailto:peter.kraker@tugraz.at\">peter.kraker@tugraz.at</a>." + "<p>The visualization was created with <a href=\"http://d3js.org/\" target=\"_blank\">D3.js</a>. It has been successfully tested with Chrome 22, Firefox 15, Safari 5.1, and Opera 20. Unfortunately, Internet Explorer is not supported at this point." + "<h5>Acknowledgements</h5>" + "<p>The visualization was created with funding provided by European Commission as part of the FP7 Marie Curie IAPP project TEAM (grant no. 251514), the Austrian Marshallplan Foundation, the Open Knowledge Foundation, and the Know-Center. The Know-Center is funded within the Austrian COMET program - Competence Centers for Excellent Technologies - under the auspices of the Austrian Federal Ministry of Transport, Innovation and Technology, the Austrian Federal Ministry of Economy, Family and Youth, and the State of Styria. COMET is managed by the Austrian Research Promotion Agency FFG."
    }
};
