# column A TO B
# https://docs.google.com/spreadsheets/d/112Anbf-sJYkehyFvjuxr1DuMih-fPB9nt3E8ll19Iyc/edit?gid=2080652987#gid=2080652987
doc_type_mapping = {
    "book": "Book",
    "book-chapter": "Book chapter",
    "conference-paper": "Conference paper",
    "conference-abstract": "Conference abstract",
    "conference-output": "Conference output",
    "conference-presentation": "Conference presentation",
    "conference-poster": "Conference poster",
    "conference-proceedings": "Conference proceedings",
    "journal-article": "Journal article",
    "preprint": "Preprint",
    "dissertation-thesis": "Dissertation thesis",
    "working-paper": "Working paper",
    "dissertation": "Dissertation",
    
    "annotation": "Annotation",
    "book-review": "Book review",
    "journal-issue": "Journal issue or edition",
    "review": "Review",
    "transcription": "Transcription",
    "translation": "Translation",

    "blog-post": "Blog post",
    "dictionary-entry": "Dictionary entry",
    "encyclopedia-entry": "Encyclopedia entry",
    "magazine-article": "Magazine article",
    "newspaper-article": "Newspaper article",
    "report": "Report",
    "public-speech": "Talk, interview, podcast or speech",
    "website": "Website",

    "artistic-performance": "Artistic output or performance",
    "design": "Design",
    "image": "Image",
    "online-resource": "Interactive resource",
    "moving-image": "Moving image or video",
    "musical-composition": "Musical composition",
    "sound": "Sound",


    "cartographic-material": "Cartographic material",
    "clinical-study": "Clinical study",
    "data-set": "Dataset",
    "data-management-plan": "Data management plan",
    "physical-object": "Physical object",
    "research-technique": "Research protocol or technique",
    "research-tool": "Research tool",
    "software": "Software",
    "other": "Other",

    "invention": "Invention",
    "license": "License",
    "patent": "Patent",
    "registered-copyright": "Registered copyright",
    "standards-and-policy": "Standards or policy",
    "trademark": "Trademark",

    "lecture-speech": "Lecture",
    "learning-object": "Teaching material",
    "supervised-student-publication": "Supervised student publication",

    "conference-abstract": "Conference abstract",
    "disclosure": "Disclosure",
    "edited-book": "Edited book",
    "manual": "Manual",
    "newsletter-article": "Newsletter article",
    "spin-off-company": "Spin-off company",
    "technical-standards": "Technical standards",
    "test": "Test",
}