version: '3.7'

services:

  proxy:
    image: 'nginx'
    volumes:
      - ./templates:/etc/nginx/templates
    environment:
      - NGINX_PORT=80
    ports:
      - '8080:80'
    networks:
      - stable_headstart

networks:
  stable_headstart:
        external: true
        name: stable_headstart