FROM python:3.7

MAINTAINER Chris Kittel "christopher.kittel@openknowledgemaps.org"

RUN apt-get update
RUN apt-get install -y --no-install-recommends gcc git python3-dev
RUN apt-get install -y libpq-dev

WORKDIR /app
RUN pip install git+https://github.com/python-restx/flask-restx
RUN pip install pytest requests sqlalchemy sqlalchemy-utils psycopg2-binary