<?php

$TOP_100_QUERIES = [
"digital education",
"pendidikan",
"hipertensi",
"ai",
"digital marketing",
"akuntansi",
"manajemen keuangan",
"covid-19",
"artificial intelligence",
"jurnal",
"marketing",
"umkm",
"stunting",
"media pembelajaran",
"machine learning",
"manajemen sumber daya manusia",
"manajemen pemasaran",
"keputusan pembelian",
"customer relationship management",
"deep learning",
"pemasaran",
"manajemen",
"kinerja karyawan",
"pendidikan karakter",
"sistem informasi",
"pendidikan agama islam",
"education",
"kinerja keuangan",
"literasi keuangan",
"green accounting",
"pajak",
"ekonomi syariah",
"media sosial",
"komunikasi",
"sistem informasi akuntansi",
"kepemimpinan",
"ekonomi",
"diabetes",
"corporate social responsibility",
"sumber daya manusia",
"perbankan syariah",
"kesehatan mental",
"nilai perusahaan",
"esg",
"diabetes melitus",
"accounting",
"akuntansi keuangan",
"audit",
"bullying",
"manajemen sdm",
"work life balance",
"kepuasan kerja",
"kewirausahaan",
"hukum",
"keuangan",
"anemia",
"psikologi",
"climate change",
"mental health",
"strategi pemasaran",
"kurikulum merdeka",
"financial distress",
"motivasi belajar",
"kepuasan pelanggan",
"tax avoidance",
"pariwisata",
"perilaku konsumen",
"perpajakan",
"kemiskinan",
"kualitas pelayanan",
"problem based learning",
"self efficacy",
"csr",
"literasi digital",
"motivasi kerja",
"manajemen pendidikan",
"moderasi beragama",
"pertumbuhan ekonomi",
"profitabilitas",
"psychology",
"finance",
"cancer",
"gender",
"investasi",
"data mining",
"zakat",
"green marketing",
"hasil belajar",
"augmented reality",
"budaya organisasi",
"pernikahan dini",
"blockchain",
"fintech",
"motivasi",
"management",
"tiktok",
"kinerja",
"brand image",
"leadership",
"social media"
];

$TOP_10_QUERIES = [
"digital education",
"pendidikan",
"hipertensi",
"ai",
"digital marketing",
"akuntansi",
"manajemen keuangan",
"covid-19",
"artificial intelligence",
"jurnal"
];

$ALL_BASE_DOC_TYPES = [
  "1",
  "11",
  "111",
  "12",
  "121",
  "122",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "181",
  "182",
  "183",
  "19",
  "1A",
  "2",
  "3",
  "4",
  "5",
  "51",
  "52",
  "6",
  "7",
  "F"
];